server:
  port: 8080

spring:
  application:
    name: api-gateway

#Auto discover from eureka service registry
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
#Above is the manual routing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka

#For security filtering skipping else filter will block also work without this to
management:
  endpoints:
    web:
      exposure:
        include: "*"
