server:
  port: 8080

spring:
  application:
    name: api-gateway


#Auto discover from eureka service registry
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: restaurant-service
              uri: lb://restaurant-service
              predicates:
                  - Path=/api/restaurants/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                      - Path=/api/delivery/**
#Above is the manual routing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/QuickBites

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka

#For security filtering skipping else filter will block also work without this to
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
